import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:speech_to_text/speech_to_text.dart' as stt;
import 'package:taptalk/scentence.dart';

class ChatPage extends StatefulWidget {
  const ChatPage({super.key});

  @override
  _ChatPageState createState() => _ChatPageState();
}

class _ChatPageState extends State<ChatPage> {
  final FlutterTts _flutterTts = FlutterTts();
  final stt.SpeechToText _speech = stt.SpeechToText();
  final TextEditingController _textController = TextEditingController();
  final List<ChatMessage> _messages = [];
  bool _isListening = false;
  bool _speechEnabled = false;
  String _recognizedText = '';
  List<String> _replySuggestions = []; // Store reply suggestions

  @override
  void initState() {
    super.initState();
    _initializeTts();
    _initializeSpeech();
  }

  void _initializeTts() async {
    await _flutterTts.setLanguage("en-US");
    await _flutterTts.setPitch(1.0);
    await _flutterTts.setSpeechRate(0.3);
  }

  void _initializeSpeech() async {
    _speechEnabled = await _speech.initialize();
    if (!_speechEnabled) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Speech recognition not available')),
      );
    }
  }

  void _sendMessage(String text, {bool isSpeechGenerated = false}) {
    if (text.trim().isEmpty) return;

    setState(() {
      // Add the message to the chat
      _messages.add(ChatMessage(text: text, isMe: !isSpeechGenerated));
      _textController.clear();

      _replySuggestions.clear();
    });

    // Play the message as speech only if it's not generated by speech-to-text
    if (!isSpeechGenerated) {
      _flutterTts.speak(text);
    }

    // Fetch reply suggestions only if the message is generated by speech-to-text
    if (isSpeechGenerated) {
      _fetchReplySuggestions(text);
    }
  }

  void _fetchReplySuggestions(String input) async {
    final apiUrl =
        Uri.parse('http://10.0.2.2:5000/generate_reply?input_text=$input');
    final response = await http.get(
      apiUrl,
      headers: {'Content-Type': 'application/json'},
    );

    if (response.statusCode == 200) {
      final responseData = jsonDecode(response.body);
      final replies = List<String>.from(responseData['replies']);

      setState(() {
        _replySuggestions = replies; // Update reply suggestions
      });
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
            content:
                Text('Failed to fetch suggestions: ${response.statusCode}')),
      );
    }
  }

  void _startListening() async {
    if (!_isListening && _speechEnabled) {
      setState(() {
        _isListening = true;
        _recognizedText = ''; // Reset recognized text
      });

      _speech.listen(
        onResult: (result) {
          setState(() {
            _recognizedText = result.recognizedWords;
          });
        },
      );
    }
  }

  void _stopListening() async {
    if (_isListening) {
      await _speech.stop();
      setState(() => _isListening = false);

      // Send the recognized text as a message from the other person
      if (_recognizedText.trim().isNotEmpty) {
        _sendMessage(_recognizedText, isSpeechGenerated: true);
      }
    }
  }

  void _showTapToTalkBottomSheet() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (context) {
        return TapToTalkBottomSheet(
          onSuggestionSelected: (sentence) {
            _sendMessage(sentence); // Send the selected sentence as a message
          },
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          "Chat",
          style: GoogleFonts.poppins(fontWeight: FontWeight.w600),
        ),
      ),
      body: Column(
        children: [
          Expanded(
            child: ListView.builder(
              itemCount: _messages.length,
              itemBuilder: (context, index) {
                return _messages[index];
              },
            ),
          ),
          // Display reply suggestions as chips
          if (_replySuggestions.isNotEmpty)
            Container(
              height: 60,
              padding: const EdgeInsets.symmetric(horizontal: 8),
              child: ListView.builder(
                scrollDirection: Axis.horizontal,
                itemCount: _replySuggestions.length,
                itemBuilder: (context, index) {
                  return Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 4),
                    child: ChoiceChip(
                      label: Text(_replySuggestions[index]),
                      selected: false,
                      onSelected: (selected) {
                        _sendMessage(_replySuggestions[index]);
                        setState(() {
                          _replySuggestions
                              .clear(); // Clear suggestions after selection
                        });
                      },
                    ),
                  );
                },
              ),
            ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Row(
              children: [
                IconButton(
                  icon: Icon(_isListening ? Icons.mic_off : Icons.mic),
                  onPressed: _isListening ? _stopListening : _startListening,
                ),
                Expanded(
                  child: TextField(
                    controller: _textController,
                    decoration: const InputDecoration(
                      hintText: 'Type a message...',
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.send),
                  onPressed: () => _sendMessage(_textController.text),
                ),
                IconButton(
                  icon: const Icon(Icons.grid_view),
                  onPressed: _showTapToTalkBottomSheet,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class ChatMessage extends StatelessWidget {
  final String text;
  final bool isMe;

  const ChatMessage({super.key, required this.text, required this.isMe});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(vertical: 4, horizontal: 8),
      alignment: isMe ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: isMe ? Colors.blue : Colors.grey[300],
          borderRadius: isMe
              ? const BorderRadius.only(
                  bottomLeft: Radius.circular(12),
                  topLeft: Radius.circular(12),
                  topRight: Radius.circular(12))
              : const BorderRadius.only(
                  bottomRight: Radius.circular(12),
                  topLeft: Radius.circular(12),
                  topRight: Radius.circular(12)),
        ),
        child: Text(
          text,
          style: TextStyle(color: isMe ? Colors.white : Colors.black),
        ),
      ),
    );
  }
}

class TapToTalkBottomSheet extends StatefulWidget {
  final Function(String) onSuggestionSelected;

  const TapToTalkBottomSheet({super.key, required this.onSuggestionSelected});

  @override
  _TapToTalkBottomSheetState createState() => _TapToTalkBottomSheetState();
}

class _TapToTalkBottomSheetState extends State<TapToTalkBottomSheet> {
  List<List<String>> wordSets = [
    [
      "I",
      "You",
      "Where",
      "Help",
      "Our",
      "Can",
      "We",
      "They",
      "Will",
      "My",
      "Should",
      "Could"
    ],
  ];

  int currentGridIndex = 0;
  final PageController _pageController = PageController();
  List<String> keywordList = [];
  List<String> sentenceList = sentenceListA;

  // Text-to-speech
  final FlutterTts flutterTts = FlutterTts();
  String? currentlyPlayingSentence;

  @override
  void initState() {
    super.initState();
    _initializeTts();
  }

  void _initializeTts() async {
    await flutterTts.setLanguage("en-US");
    await flutterTts.setPitch(1);
    await flutterTts.setSpeechRate(0.3);
    await flutterTts.awaitSpeakCompletion(true);
  }

  void _playSentence(String sentence) async {
    if (currentlyPlayingSentence == sentence) {
      await flutterTts.stop();
      setState(() {
        currentlyPlayingSentence = null;
      });
    } else {
      await flutterTts.stop();
      setState(() {
        currentlyPlayingSentence = sentence;
      });

      await flutterTts.speak(sentence);

      await flutterTts.awaitSpeakCompletion(true);

      setState(() {
        currentlyPlayingSentence = null;
      });
    }
  }

  void _handleKeywordSelection(String keyword) async {
    setState(() {
      keywordList.add(keyword);
    });

    await _generateNextKeywords();
  }

  void _clearKeywords() {
    setState(() {
      keywordList.clear();
      if (wordSets.isNotEmpty) {
        wordSets = [wordSets[0]];
      }
      currentGridIndex = 0;
      _pageController.animateToPage(
        0,
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeInOut,
      );
    });
  }

  Future<void> _generateNextKeywords() async {
    final inputText = keywordList.join(' ');

    final apiUrl = Uri.parse(
        'http://10.0.2.2:5000/predict_next_word?input_text=$inputText');

    final response = await http.get(apiUrl);

    if (response.statusCode == 200) {
      final responseData = jsonDecode(response.body);
      final nextKeywords = List<String>.from(responseData['suggestions']);

      setState(() {
        wordSets.add(nextKeywords);
        currentGridIndex++;
        _pageController.animateToPage(
          currentGridIndex,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeInOut,
        );
      });
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
            content:
                Text('Failed to generate keywords: ${response.statusCode}')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Container(
      height: MediaQuery.of(context).size.height * 0.7,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: theme.colorScheme.surface,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
      ),
      child: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Tap to Talk',
                style: TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                  color: theme.colorScheme.onSurface,
                ),
              ),
              IconButton(
                icon: Icon(
                  Icons.clear,
                  color: theme.colorScheme.onSurface,
                ),
                onPressed: () => Navigator.pop(context),
              ),
            ],
          ),
          Expanded(
            child: PageView.builder(
              controller: _pageController,
              itemCount: wordSets.length,
              onPageChanged: (index) {
                setState(() {
                  currentGridIndex = index;
                });
              },
              itemBuilder: (context, index) {
                final currentWords = wordSets[index];
                return GridView.builder(
                  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 3,
                    crossAxisSpacing: 10,
                    mainAxisSpacing: 10,
                    childAspectRatio: 1,
                  ),
                  itemCount: currentWords.length,
                  itemBuilder: (context, index) {
                    return GestureDetector(
                      onTap: () => _handleKeywordSelection(currentWords[index]),
                      child: Container(
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(6),
                          border: Border.all(
                            color: theme.colorScheme.onSurface,
                            width: 2,
                          ),
                        ),
                        child: Center(
                          child: Text(
                            textAlign: TextAlign.center,
                            currentWords[index],
                            style: GoogleFonts.poppins(
                              fontSize: 18,
                              fontWeight: FontWeight.w600,
                              color: theme.colorScheme.onSurface,
                            ),
                          ),
                        ),
                      ),
                    );
                  },
                );
              },
            ),
          ),
          if (keywordList.isNotEmpty)
            Expanded(
              child: ListView.builder(
                itemCount: sentenceList.where((sentence) {
                  return _containsKeywords(sentence, keywordList);
                }).length,
                itemBuilder: (context, index) {
                  final matchedSentences = sentenceList.where((sentence) {
                    return _containsKeywords(sentence, keywordList);
                  }).toList();
                  final sentence = matchedSentences[index];
                  return ListTile(
                    leading: currentlyPlayingSentence == sentence
                        ? Icon(
                            Icons.volume_up,
                            color: theme.colorScheme.onSurface,
                          )
                        : null,
                    title: Text(
                      sentence,
                      style: TextStyle(
                        color: theme.colorScheme.onSurface,
                      ),
                    ),
                    onTap: () {
                      widget.onSuggestionSelected(sentence);
                      Navigator.pop(context);
                    },
                  );
                },
              ),
            ),
        ],
      ),
    );
  }

  bool _containsKeywords(String sentence, List<String> keywords) {
    final wordsInSentence = sentence.toLowerCase().split(RegExp(r'\W+'));
    return keywords
        .every((keyword) => wordsInSentence.contains(keyword.toLowerCase()));
  }
}
